plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
title: Homepage for sigunning.github
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
## theme: jekyll-theme-minimal
theme: jekyll-theme-minima

### Supported Jeckyll themes
## https://pages.github.com/themes/
## Architect
## Cayman
## Dinky
## Hacker
## Leap day
## Merlot
## Midnight
## Minima
## Minimal
## Modernist
## Slate
## Tactile
## Time machine